const START_POINTS = [
  { title: "Italia", lat: 41.9, lon: 12.5, images: [ "images/italia.png"] },
  { title: "Francia", lat: 46.2, lon: 2.2, images: ["images/francia.png"] },
  { title: "Germania", lat: 51.2, lon: 10.4, images: ["images/germania.png"] },
  { title: "Regno Unito", lat: 54.0, lon: -2.0, images: ["images/regnounito.png"] },
  { title: "Spagna", lat: 40.4, lon: -3.7, images: ["images/spagna.png"] },
  { title: "Polonia", lat: 52.1, lon: 19.1, images: ["images/polonia.png"] },
  { title: "Grecia", lat: 39.1, lon: 22.9, images: ["images/grecia.png"] },
  { title: "Russia", lat: 60.0, lon: 90.0, images: ["images/russia.png"] },
  { title: "Egitto", lat: 26.8, lon: 30.8, images: ["images/egitto.png"] },
  { title: "Marocco", lat: 31.8, lon: -7.1, images: ["images/marocco.png"] },
  { title: "Nigeria", lat: 9.1, lon: 8.7, images: ["images/nigeria.png"] },
  { title: "Etiopia", lat: 9.1, lon: 40.5, images: ["images/etiopia.png"] },
  { title: "Kenya", lat: 0.0, lon: 37.9, images: ["images/kenya.png"] },
  { title: "Sudafrica", lat: -30.6, lon: 22.9, images: ["images/sudafrica.png"] },
  { title: "Ghana", lat: 7.9, lon: -1.0, images: ["images/ghana.png"] },
  { title: "Stati Uniti", lat: 39.8, lon: -98.6, images: ["images/statiuniti.png"] },
  { title: "Canada", lat: 56.1, lon: -106.3, images: ["images/canada.png.png"] },
  { title: "Messico", lat: 23.6, lon: -102.5, images: ["images/messico.png"] },
  { title: "Brasile", lat: -14.2, lon: -51.9, images: ["images/brasile.png"] },
  { title: "Argentina", lat: -38.4, lon: -63.6, images: ["images/argentina.png"] },
  { title: "Cile", lat: -33.4, lon: -71.0, images: ["images/cile.png"] },
  { title: "Cina", lat: 35.9, lon: 104.2, images: ["images/cina.png"] },
  { title: "India", lat: 22.0, lon: 79.0, images: ["images/india.png"] },
  { title: "Giappone", lat: 36.2, lon: 138.3, images: ["images/giappone.png"] },
  { title: "Indonesia", lat: -2.5, lon: 118.0, images: ["images/indonesia.png"] },
  { title: "Arabia Saudita", lat: 23.9, lon: 45.1, images: ["images/arabiasaudita.png"] },
  { title: "Thailandia", lat: 15.8, lon: 101.0, images: ["images/thailandia.png"] },
  { title: "Kazakhstan", lat: 48.0, lon: 67.0, images: ["images/kazakhstan.png"] },
  { title: "Turchia", lat: 39.0, lon: 35.0, images: ["images/turchia.png"] },
  { title: "Israele", lat: 31.0, lon: 35.0, images: ["images/israele.png"] },
  { title: "Iran", lat: 32.4, lon: 53.7, images: ["images/iran.png"] },
  { title: "Australia", lat: -25.3, lon: 133.8, images: ["images/australia.png"] },
  { title: "Nuova Zelanda", lat: -41.3, lon: 174.8, images: ["images/nuovazelanda.png"] },
  { title: "Papua Nuova Guinea", lat: -6.3, lon: 145.1, images: ["images/papua.png"] },
  { title: "Figi", lat: -17.7, lon: 178.1, images: ["images/figi.png"] },
  { title: "Norvegia", lat: 60.5, lon: 8.5, images: ["images/norvegia.png"] },
  { title: "Svezia", lat: 60.1, lon: 18.6, images: ["images/svezia.png"] },
  { title: "Portogallo", lat: 39.6, lon: -8.1, images: ["images/portogallo.png"] },
  { title: "Corea del Sud", lat: 36.5, lon: 127.9, images: ["images/coreadelsud.png"] }
];
